/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as TokenRouteImport } from './routes/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/channel': typeof ChannelRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/requests': typeof RequestsRoute
  '/token': typeof TokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/channel': typeof ChannelRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/requests': typeof RequestsRoute
  '/token': typeof TokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/channel': typeof ChannelRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/requests': typeof RequestsRoute
  '/token': typeof TokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/channel'
    | '/config'
    | '/login'
    | '/models'
    | '/overview'
    | '/pricing'
    | '/requests'
    | '/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/channel'
    | '/config'
    | '/login'
    | '/models'
    | '/overview'
    | '/pricing'
    | '/requests'
    | '/token'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/channel'
    | '/config'
    | '/login'
    | '/models'
    | '/overview'
    | '/pricing'
    | '/requests'
    | '/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChannelRoute: typeof ChannelRoute
  ConfigRoute: typeof ConfigRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  OverviewRoute: typeof OverviewRoute
  PricingRoute: typeof PricingRoute
  RequestsRoute: typeof RequestsRoute
  TokenRoute: typeof TokenRoute
}

declare module '@tanstack/vue-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChannelRoute: ChannelRoute,
  ConfigRoute: ConfigRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  OverviewRoute: OverviewRoute,
  PricingRoute: PricingRoute,
  RequestsRoute: RequestsRoute,
  TokenRoute: TokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
